

	const statesList = [		
		{ 'state'	: 'AL',	'name'	: 'Alabama'},
		{ 'state'	: 'AK',	'name'	: 'Alaska'},
		{ 'state'	: 'AS',	'name'	: 'American Samoa'},
		{ 'state'	: 'AZ',	'name'	: 'Arizona'},
		{ 'state'	: 'AR',	'name'	: 'Arkansas'},
		{ 'state'	: 'CA',	'name'	: 'California'},
		{ 'state'	: 'CO',	'name'	: 'Colorado'},
		{ 'state'	: 'CT',	'name'	: 'Connecticut'},
		{ 'state'	: 'DE',	'name'	: 'Delaware'},
		{ 'state'	: 'DC',	'name'	: 'District Of Columbia'},
		{ 'state'	: 'FM',	'name'	: 'Federated States Of Micronesia'},
		{ 'state'	: 'FL',	'name'	: 'Florida'},
		{ 'state'	: 'GA',	'name'	: 'Georgia'},
		{ 'state'	: 'GU',	'name'	: 'Guam'},
		{ 'state'	: 'HI',	'name'	: 'Hawaii'},
		{ 'state'	: 'ID',	'name'	: 'Idaho'},
		{ 'state'	: 'IL',	'name'	: 'Illinois'},
		{ 'state'	: 'IN',	'name'	: 'Indiana'},
		{ 'state'	: 'IA',	'name'	: 'Iowa'},
		{ 'state'	: 'KS',	'name'	: 'Kansas'},
		{ 'state'	: 'KY',	'name'	: 'Kentucky'},
		{ 'state'	: 'LA',	'name'	: 'Louisiana'},
		{ 'state'	: 'ME',	'name'	: 'Maine'},
		{ 'state'	: 'MH',	'name'	: 'Marshall Islands'},
		{ 'state'	: 'MD',	'name'	: 'Maryland'},
		{ 'state'	: 'MA',	'name'	: 'Massachusetts'},
		{ 'state'	: 'MI',	'name'	: 'Michigan'},
		{ 'state'	: 'MN',	'name'	: 'Minnesota'},
		{ 'state'	: 'MS',	'name'	: 'Mississippi'},
		{ 'state'	: 'MO',	'name'	: 'Missouri'},
		{ 'state'	: 'MT',	'name'	: 'Montana'},
		{ 'state'	: 'NE',	'name'	: 'Nebraska'},
		{ 'state'	: 'NV',	'name'	: 'Nevada'},
		{ 'state'	: 'NH',	'name'	: 'New Hampshire'},
		{ 'state'	: 'NJ',	'name'	: 'New Jersey'},
		{ 'state'	: 'NM',	'name'	: 'New Mexico'},
		{ 'state'	: 'NY',	'name'	: 'New York'},
		{ 'state'	: 'NC',	'name'	: 'North Carolina'},
		{ 'state'	: 'ND',	'name'	: 'North Dakota'},
		{ 'state'	: 'MP',	'name'	: 'Northern Mariana Islands'},
		{ 'state'	: 'OH',	'name'	: 'Ohio'},
		{ 'state'	: 'OK',	'name'	: 'Oklahoma'},
		{ 'state'	: 'OR',	'name'	: 'Oregon'},
		{ 'state'	: 'PW',	'name'	: 'Palau'},
		{ 'state'	: 'PA',	'name'	: 'Pennsylvania'},
		{ 'state'	: 'PR',	'name'	: 'Puerto Rico'},
		{ 'state'	: 'RI',	'name'	: 'Rhode Island'},
		{ 'state'	: 'SC',	'name'	: 'South Carolina'},
		{ 'state'	: 'SD',	'name'	: 'South Dakota'},
		{ 'state'	: 'TN',	'name'	: 'Tennessee'},
		{ 'state'	: 'TX',	'name'	: 'Texas'},
		{ 'state'	: 'UM',	'name'	: 'United States Minor Outlying Islands'},
		{ 'state'	: 'UT',	'name'	: 'Utah'},
		{ 'state'	: 'VT',	'name'	: 'Vermont'},
		{ 'state'	: 'VI',	'name'	: 'Virgin Islands'},
		{ 'state'	: 'VA',	'name'	: 'Virginia'},
		{ 'state'	: 'WA',	'name'	: 'Washington'},
		{ 'state'	: 'WV',	'name'	: 'West Virginia'},
		{ 'state'	: 'WI',	'name'	: 'Wisconsin'},
		{ 'state'	: 'WY',	'name'	: 'Wyoming'},		
		{ 'state'	: 'AB',	'name' 	: 'Alberta'},
		{ 'state'	: 'BC',	'name' 	: 'British Columbia'},
		{ 'state'	: 'MB',	'name' 	: 'Manitoba'},
		{ 'state'	: 'NB',	'name' 	: 'New Brunswick'},
		{ 'state'	: 'NL',	'name' 	: 'Newfoundland and Labrador'},
		{ 'state'	: 'NS',	'name' 	: 'Nova Scotia'},
		{ 'state'	: 'ON',	'name' 	: 'Ontario'},
		{ 'state'	: 'PE',	'name' 	: 'Prince Edward Island'},
		{ 'state'	: 'QC',	'name' 	: 'Quebec'},
		{ 'state'	: 'SK',	'name' 	: 'Saskatchewan'},
		{ 'state'	: 'NT',	'name' 	: 'Northwest Territories'},
		{ 'state'	: 'NU',	'name' 	: 'Nunavut'},
		{ 'state'	: 'YT',	'name' 	: 'Yukon'},		
	]
	
   
   const eventDuration =  [
      { 'time': '30', 'text': '30 minutes'},
      { 'time': '60', 'text' : 'one hour'},
      { 'time': '90', 'text' : '90 minutes'},
      { 'time': '120', 'text': 'Two hours'},
      { 'time': '180', 'text': 'Three hours'},
      { 'time': '240', 'text': 'Four hours'},
      { 'time': '300', 'text': 'Five hours'},
      { 'time': '360', 'text': 'Six hours'},
      { 'time': '480', 'text': 'Eight hours'},
      { 'time': '600', 'text': 'Ten hours'},
      { 'time': '720', 'text': 'Twelve hours'},
   ]
            
   
   const experienceLevels = [
      {'level' : '1', 'text': 'beginner'},
      {'level' : '2', 'text': 'familiar'},
      {'level' : '3', 'text': 'expert'},
   ]

   
   
	export { statesList, eventDuration, experienceLevels }

   